//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xfrogcn.BinaryFormatter.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Xfrogcn.BinaryFormatter.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BinaryIncludeOnNonPublicInvalid {
            get {
                return ResourceManager.GetString("BinaryIncludeOnNonPublicInvalid", resourceCulture);
            }
        }
        
        internal static string CannotPopulateCollection {
            get {
                return ResourceManager.GetString("CannotPopulateCollection", resourceCulture);
            }
        }
        
        internal static string CannotSerializeInvalidMember {
            get {
                return ResourceManager.GetString("CannotSerializeInvalidMember", resourceCulture);
            }
        }
        
        internal static string CannotSerializeInvalidType {
            get {
                return ResourceManager.GetString("CannotSerializeInvalidType", resourceCulture);
            }
        }
        
        internal static string ConstructorMaxOf64Parameters {
            get {
                return ResourceManager.GetString("ConstructorMaxOf64Parameters", resourceCulture);
            }
        }
        
        internal static string ConstructorParamIncompleteBinding {
            get {
                return ResourceManager.GetString("ConstructorParamIncompleteBinding", resourceCulture);
            }
        }
        
        internal static string ConverterCanConvertNullableRedundant {
            get {
                return ResourceManager.GetString("ConverterCanConvertNullableRedundant", resourceCulture);
            }
        }
        
        internal static string DefaultIgnoreConditionAlreadySpecified {
            get {
                return ResourceManager.GetString("DefaultIgnoreConditionAlreadySpecified", resourceCulture);
            }
        }
        
        internal static string DefaultIgnoreConditionInvalid {
            get {
                return ResourceManager.GetString("DefaultIgnoreConditionInvalid", resourceCulture);
            }
        }
        
        internal static string DepthTooLarge {
            get {
                return ResourceManager.GetString("DepthTooLarge", resourceCulture);
            }
        }
        
        internal static string DeserializeNoConstructor {
            get {
                return ResourceManager.GetString("DeserializeNoConstructor", resourceCulture);
            }
        }
        
        internal static string DeserializeUnableToConvertValue {
            get {
                return ResourceManager.GetString("DeserializeUnableToConvertValue", resourceCulture);
            }
        }
        
        internal static string ExpectedBinaryTokens {
            get {
                return ResourceManager.GetString("ExpectedBinaryTokens", resourceCulture);
            }
        }
        
        internal static string ExtensionDataCannotBindToCtorParam {
            get {
                return ResourceManager.GetString("ExtensionDataCannotBindToCtorParam", resourceCulture);
            }
        }
        
        internal static string FailedToGetLargerSpan {
            get {
                return ResourceManager.GetString("FailedToGetLargerSpan", resourceCulture);
            }
        }
        
        internal static string IgnoreConditionOnValueTypeInvalid {
            get {
                return ResourceManager.GetString("IgnoreConditionOnValueTypeInvalid", resourceCulture);
            }
        }
        
        internal static string InvalidCast {
            get {
                return ResourceManager.GetString("InvalidCast", resourceCulture);
            }
        }
        
        internal static string MaxDepthMustBePositive {
            get {
                return ResourceManager.GetString("MaxDepthMustBePositive", resourceCulture);
            }
        }
        
        internal static string MultipleMembersBindWithConstructorParameter {
            get {
                return ResourceManager.GetString("MultipleMembersBindWithConstructorParameter", resourceCulture);
            }
        }
        
        internal static string SerializationConverterNotCompatible {
            get {
                return ResourceManager.GetString("SerializationConverterNotCompatible", resourceCulture);
            }
        }
        
        internal static string SerializationConverterOnAttributeInvalid {
            get {
                return ResourceManager.GetString("SerializationConverterOnAttributeInvalid", resourceCulture);
            }
        }
        
        internal static string SerializationConverterOnAttributeNotCompatible {
            get {
                return ResourceManager.GetString("SerializationConverterOnAttributeNotCompatible", resourceCulture);
            }
        }
        
        internal static string SerializationConverterRead {
            get {
                return ResourceManager.GetString("SerializationConverterRead", resourceCulture);
            }
        }
        
        internal static string SerializationConverterWrite {
            get {
                return ResourceManager.GetString("SerializationConverterWrite", resourceCulture);
            }
        }
        
        internal static string SerializationDataExtensionPropertyInvalid {
            get {
                return ResourceManager.GetString("SerializationDataExtensionPropertyInvalid", resourceCulture);
            }
        }
        
        internal static string SerializationDuplicateAttribute {
            get {
                return ResourceManager.GetString("SerializationDuplicateAttribute", resourceCulture);
            }
        }
        
        internal static string SerializationDuplicateTypeAttribute {
            get {
                return ResourceManager.GetString("SerializationDuplicateTypeAttribute", resourceCulture);
            }
        }
        
        internal static string SerializationNotSupportedParentType {
            get {
                return ResourceManager.GetString("SerializationNotSupportedParentType", resourceCulture);
            }
        }
        
        internal static string SerializationNotSupportedType {
            get {
                return ResourceManager.GetString("SerializationNotSupportedType", resourceCulture);
            }
        }
        
        internal static string SerializeInvalidFormat {
            get {
                return ResourceManager.GetString("SerializeInvalidFormat", resourceCulture);
            }
        }
        
        internal static string SerializerConverterFactoryReturnsNull {
            get {
                return ResourceManager.GetString("SerializerConverterFactoryReturnsNull", resourceCulture);
            }
        }
        
        internal static string SerializerCycleDetected {
            get {
                return ResourceManager.GetString("SerializerCycleDetected", resourceCulture);
            }
        }
        
        internal static string SerializerPropertyNameConflict {
            get {
                return ResourceManager.GetString("SerializerPropertyNameConflict", resourceCulture);
            }
        }
        
        internal static string SerializerPropertyNameNull {
            get {
                return ResourceManager.GetString("SerializerPropertyNameNull", resourceCulture);
            }
        }
        
        internal static string SerializeUnableToSerialize {
            get {
                return ResourceManager.GetString("SerializeUnableToSerialize", resourceCulture);
            }
        }
    }
}
