//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xfrogcn.BinaryFormatter.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xfrogcn.BinaryFormatter.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;IgnoreNullValues&apos; and &apos;DefaultIgnoreCondition&apos; cannot both be set to non-default values. 的本地化字符串。
        /// </summary>
        internal static string DefaultIgnoreConditionAlreadySpecified {
            get {
                return ResourceManager.GetString("DefaultIgnoreConditionAlreadySpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value cannot be &apos;BinaryIgnoreCondition.Always&apos;. 的本地化字符串。
        /// </summary>
        internal static string DefaultIgnoreConditionInvalid {
            get {
                return ResourceManager.GetString("DefaultIgnoreConditionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Binary value could not be converted to {0}. 的本地化字符串。
        /// </summary>
        internal static string DeserializeUnableToConvertValue {
            get {
                return ResourceManager.GetString("DeserializeUnableToConvertValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ignore condition &apos;BinaryIgnoreCondition.WhenWritingNull&apos; is not valid on value-type member &apos;{0}&apos; on type &apos;{1}&apos;. Consider using &apos;BinaryIgnoreCondition.WhenWritingDefault&apos;. 的本地化字符串。
        /// </summary>
        internal static string IgnoreConditionOnValueTypeInvalid {
            get {
                return ResourceManager.GetString("IgnoreConditionOnValueTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The unsupported member type is located on type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string SerializationNotSupportedParentType {
            get {
                return ResourceManager.GetString("SerializationNotSupportedParentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Binary property name for &apos;{0}.{1}&apos; collides with another property. 的本地化字符串。
        /// </summary>
        internal static string SerializerPropertyNameConflict {
            get {
                return ResourceManager.GetString("SerializerPropertyNameConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Binary property name for &apos;{0}.{1}&apos; cannot be null. 的本地化字符串。
        /// </summary>
        internal static string SerializerPropertyNameNull {
            get {
                return ResourceManager.GetString("SerializerPropertyNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The object or value could not be serialized. 的本地化字符串。
        /// </summary>
        internal static string SerializeUnableToSerialize {
            get {
                return ResourceManager.GetString("SerializeUnableToSerialize", resourceCulture);
            }
        }
    }
}
